#!/usr/bin/env python3
import argparse
import csv
import contextlib
import wave
from pathlib import Path


def parse_args():
    p = argparse.ArgumentParser(
        description="Align webMUSHRA trial audio lengths by zero-padding to per-trial max length."
    )
    p.add_argument(
        "--trial-csv",
        default="configs/generated/text2rir_but_mushra_trials.csv",
        help="Trial CSV generated by build_text2rir_but_mushra.py",
    )
    p.add_argument(
        "--repo-root",
        default=".",
        help="Repository root containing referenced relative paths.",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Only report changes without writing files.",
    )
    return p.parse_args()


def wav_info(path: Path):
    with contextlib.closing(wave.open(str(path), "rb")) as w:
        return {
            "nchannels": w.getnchannels(),
            "sampwidth": w.getsampwidth(),
            "framerate": w.getframerate(),
            "nframes": w.getnframes(),
            "comptype": w.getcomptype(),
            "compname": w.getcompname(),
        }


def pad_wav_to_frames(path: Path, target_frames: int, dry_run: bool = False):
    with contextlib.closing(wave.open(str(path), "rb")) as w:
        params = w.getparams()
        raw = w.readframes(w.getnframes())
        current_frames = w.getnframes()

    if current_frames == target_frames:
        return False, current_frames
    if current_frames > target_frames:
        # Keep behavior explicit: truncate only if needed, but this script targets pad-to-max so shouldn't happen.
        frame_size = params.nchannels * params.sampwidth
        raw = raw[: target_frames * frame_size]
    else:
        frame_size = params.nchannels * params.sampwidth
        raw += b"\x00" * ((target_frames - current_frames) * frame_size)

    if not dry_run:
        with contextlib.closing(wave.open(str(path), "wb")) as w:
            w.setparams(params)
            w.writeframes(raw)
    return True, current_frames


def main():
    args = parse_args()
    repo = Path(args.repo_root).resolve()
    trial_csv = (repo / args.trial_csv).resolve() if not Path(args.trial_csv).is_absolute() else Path(args.trial_csv)

    if not trial_csv.exists():
        raise FileNotFoundError(f"Trial CSV not found: {trial_csv}")

    changed_files = 0
    changed_trials = 0
    max_pad_frames = 0

    with trial_csv.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            audio_keys = ["reference_url"] + [k for k in row.keys() if k.startswith("stim_")]
            # Deduplicate paths within trial (reference_url and hidden ref may point to same file).
            trial_paths = []
            seen = set()
            for key in audio_keys:
                rel = row.get(key)
                if not rel:
                    continue
                # Only WAV paths need alignment.
                if not rel.lower().endswith(".wav"):
                    continue
                if rel in seen:
                    continue
                seen.add(rel)
                path = repo / rel
                if not path.exists():
                    raise FileNotFoundError(f"Referenced audio not found: {path}")
                trial_paths.append(path)

            infos = [wav_info(p) for p in trial_paths]
            if not infos:
                continue

            # Consistency checks: samplerate/channels/sampwidth must already match.
            sr = infos[0]["framerate"]
            ch = infos[0]["nchannels"]
            sw = infos[0]["sampwidth"]
            for p, info in zip(trial_paths, infos):
                if info["framerate"] != sr or info["nchannels"] != ch or info["sampwidth"] != sw:
                    raise RuntimeError(
                        f"Format mismatch in trial {row.get('trial_index')}: {p} "
                        f"(sr={info['framerate']}, ch={info['nchannels']}, sw={info['sampwidth']}) "
                        f"!= expected (sr={sr}, ch={ch}, sw={sw})"
                    )

            max_frames = max(info["nframes"] for info in infos)
            if any(info["nframes"] != max_frames for info in infos):
                changed_trials += 1

            for p, info in zip(trial_paths, infos):
                changed, old_frames = pad_wav_to_frames(p, max_frames, dry_run=args.dry_run)
                if changed:
                    changed_files += 1
                    pad_frames = max_frames - old_frames
                    if pad_frames > max_pad_frames:
                        max_pad_frames = pad_frames

    mode = "DRY-RUN" if args.dry_run else "DONE"
    print(f"[{mode}] Trials adjusted: {changed_trials}")
    print(f"[{mode}] Files padded/truncated: {changed_files}")
    print(f"[{mode}] Max added frames: {max_pad_frames}")


if __name__ == "__main__":
    main()
